language: php

env:
  - FLAG=
  - FLAG=--prefer-lowest
  - FLAG=--prefer-stable

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - composer update ${FLAG}

script: ./build.sh

after_success:
  - vendor/bin/test-reporter